"""change geography page column name

Revision ID: 36059817c75b
Revises: d10a4c865c31
Create Date: 2024-01-22 14:25:39.457602

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '36059817c75b'
down_revision: Union[str, None] = 'd10a4c865c31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('geography_page', sa.Column('table_data', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.drop_column('geography_page', 'tables')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('geography_page', sa.Column('tables', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('geography_page', 'table_data')
    # ### end Alembic commands ###
