"""init main page table

Revision ID: 427fa99cd28b
Revises: 6e429ad39627
Create Date: 2024-01-21 16:45:52.816000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '427fa99cd28b'
down_revision: Union[str, None] = '6e429ad39627'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('main_page',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('value', sa.String(length=10), nullable=False),
    sa.Column('vacancy_name', sa.String(length=30), nullable=False),
    sa.Column('first_paragraph', sa.String(length=3000), nullable=False),
    sa.Column('second_paragraph_name', sa.String(length=30), nullable=False),
    sa.Column('second_paragraph', sa.String(length=3000), nullable=False),
    sa.Column('img_paths', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('main_page')
    # ### end Alembic commands ###
