"""geography page table added

Revision ID: d10a4c865c31
Revises: 730376f070f7
Create Date: 2024-01-22 04:24:59.577162

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd10a4c865c31'
down_revision: Union[str, None] = '730376f070f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('geography_page',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('value', sa.String(length=10), nullable=False),
    sa.Column('tables', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('img_path', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('geography_page')
    # ### end Alembic commands ###
