"""vacancy name table deleted

Revision ID: f22e96abb9ab
Revises: f92bc35ab301
Create Date: 2024-01-24 01:21:57.349613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f22e96abb9ab'
down_revision: Union[str, None] = 'f92bc35ab301'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('current_vacancy')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('current_vacancy',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('value', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('vacancy_name', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='current_vacancy_pkey')
    )
    # ### end Alembic commands ###
